/* Generated By:JavaCC: Do not edit this line. DBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int CREATE = 6;
  /** RegularExpression Id. */
  int TABLE = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int NULL = 9;
  /** RegularExpression Id. */
  int PRIMARY = 10;
  /** RegularExpression Id. */
  int KEY = 11;
  /** RegularExpression Id. */
  int FOREIGN = 12;
  /** RegularExpression Id. */
  int REFERENCES = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int CHAR = 15;
  /** RegularExpression Id. */
  int DATE = 16;
  /** RegularExpression Id. */
  int DROP = 17;
  /** RegularExpression Id. */
  int SHOW = 18;
  /** RegularExpression Id. */
  int TABLES = 19;
  /** RegularExpression Id. */
  int DESC = 20;
  /** RegularExpression Id. */
  int SELECT = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int FROM = 23;
  /** RegularExpression Id. */
  int WHERE = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int IS = 27;
  /** RegularExpression Id. */
  int INSERT = 28;
  /** RegularExpression Id. */
  int INTO = 29;
  /** RegularExpression Id. */
  int VALUES = 30;
  /** RegularExpression Id. */
  int DELETE = 31;
  /** RegularExpression Id. */
  int ALTER = 32;
  /** RegularExpression Id. */
  int ADD = 33;
  /** RegularExpression Id. */
  int COUNT = 34;
  /** RegularExpression Id. */
  int SUM = 35;
  /** RegularExpression Id. */
  int AVG = 36;
  /** RegularExpression Id. */
  int SEMICOLON = 37;
  /** RegularExpression Id. */
  int LEFT_PAREN = 38;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 39;
  /** RegularExpression Id. */
  int PERIOD = 40;
  /** RegularExpression Id. */
  int COMMA = 41;
  /** RegularExpression Id. */
  int UNDERSCORE = 42;
  /** RegularExpression Id. */
  int QUOTE = 43;
  /** RegularExpression Id. */
  int LEFT_PEAK = 44;
  /** RegularExpression Id. */
  int RIGHT_PEAK = 45;
  /** RegularExpression Id. */
  int INT_VALUE = 46;
  /** RegularExpression Id. */
  int SIGN = 47;
  /** RegularExpression Id. */
  int DIGIT = 48;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 49;
  /** RegularExpression Id. */
  int ALPHABET = 50;
  /** RegularExpression Id. */
  int CHAR_STRING = 51;
  /** RegularExpression Id. */
  int NNNN = 52;
  /** RegularExpression Id. */
  int NN = 53;
  /** RegularExpression Id. */
  int DATE_VALUE = 54;
  /** RegularExpression Id. */
  int STAR = 55;
  /** RegularExpression Id. */
  int EQUAL = 56;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 57;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"create\"",
    "\"table\"",
    "\"not\"",
    "\"null\"",
    "\"primary\"",
    "\"key\"",
    "\"foreign\"",
    "\"references\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"drop\"",
    "\"show\"",
    "\"tables\"",
    "\"desc\"",
    "\"select\"",
    "\"as\"",
    "\"from\"",
    "\"where\"",
    "\"or\"",
    "\"and\"",
    "\"is\"",
    "\"insert\"",
    "\"into\"",
    "\"values\"",
    "\"delete\"",
    "\"alter\"",
    "\"add\"",
    "\"count\"",
    "\"sum\"",
    "\"avg\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"_\"",
    "\"\\\'\"",
    "\"<\"",
    "\">\"",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<CHAR_STRING>",
    "<NNNN>",
    "<NN>",
    "<DATE_VALUE>",
    "\"*\"",
    "\"=\"",
    "<NON_QUOTE_CHARACTER>",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
  };

}
